### ISSUE TITLE
require issue

### ISSUE THREAD

**Issue by LintaoAmons** [airpods69/yagp.nvim#1]
![image](https://github.com/airpods69/yagp.nvim/assets/95092244/ce1e7551-1511-4ff3-a9ff-c26f3c7ead42)

**Comment by airpods69** [comment]
Got it! 
I'll do it in an hour or something (I'll switch to planetary.nvim as well for curl)

**Comment by airpods69** [comment]
Fixed this one and it should be fine now.

https://github.com/airpods69/yagp.nvim/blob/9c9a06b537ebfc2048a020b7cda8457b36c4d478/lua/yagp/init.lua#L14
